### ISSUE TITLE
Stable serialization for psbt inputs/outputs

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/libwally-core#214]
c-lightning has a requirement that we can identify modified PSBT entries (inputs + outputs). The comparison function we're using currently uses a linearized form of the PSBT to do a comparison, however this will fail for input/outputs that have identical yet unordered maps as the map data is not sorted before serialization.

Either we should update serialization to be 'stable' i.e. sort all maps before serialization, or add a comparison function.

**Comment by jgriffiths** [comment]
@niftynei a comparison function would be my preferred choice. Do you need a lexicographical compare or just an equality function?

**Comment by jgriffiths** [comment]
@niftynei Please try the above PR. If you sort your input/output maps before linearizing them that should work for you until such time as comparison gets exposed.

**Comment by jgriffiths** [comment]
Another possibility here to detect changes is to merge any maps being compared and see if their length changes, since adding items ignores duplicates (and under PSBT rules new values in the map entries can be ignored since either old or new values can be chosen).

Looking at the comparison as done by c-lightning I'm going to close this for now, I don't think a compare function thats sufficiently powerful and generic can really be implemented at the library level; for app specific use there is always going to be some bespoke processing that requires custom checking.
