### ISSUE TITLE
WALLY_MINISCRIPT_REQUIRE_CHECKSUM flag missing in docs

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#367]

**Comment by jgriffiths** [comment]
The docs were written originally for doxygen, but I ended up using sphinx because the output is so much nicer. Unfortunately the sphinx docs don't include API constants yet but this should be done for all constants.

In the meantime, all flags/constants are documented in the header files as a workaround.

**Comment by jgriffiths** [comment]
Added docs for all constants, please see https://wally.readthedocs.io/en/latest/

**Comment by Sjors** [comment]
Thanks!
